# configs/datamodule/ae.yaml

_target_: deepfusion.datamodules.ae_datamodule.AE_DataModule
data_dir: data
batch_size: 8
use_sampler: true
num_workers: 0
pin_memory: false
use_subset: false        # set true for quick smoke tests

