# configs/datamodule/ae.yaml

_target_: deepfusion.datamodules.ae_datamodule.AE_DataModule
data_dir: data
batch_size: 24
use_sampler: true
num_workers: 2
pin_memory: true
use_subset: false        # set true for quick smoke tests