# configs/datamodule/ae.yaml

_target_: deepfusion.datamodules.ae_datamodule.AEDataModule
data_dir: data
batch_size: 2
use_sampler: true
num_workers: 12
pin_memory: true
use_subset: false        # set true for quick smoke tests
prefetch_factor: 2

