_target_: deepfusion.utils.finetuner.build_finetuner_from_pretrained

# REQUIRED: point to your SSL (DeepFusion) checkpoint
ssl_ckpt_path: logs/pretraining-DeepFusion/train/version_25/checkpoints/best-epoch:117-val_loss:0.1162.ckpt

# Finetuner constructor args (Hydra-overridable at CLI)
task: ${hydra:runtime.choices.task}   # keep task in sync with /configs/task/*
lr: 1e-5
weight_decay: 0.05
betas: [0.9, 0.999]
dropout: 0.1

# you can also override e.g. dim_feedforward, num_head here if you really need